### ISSUE TITLE
Confusing Classification Error

### ISSUE THREAD

**Issue by ArsenLuca** [hustvl/MaskAdapter#1] opened 2024-12-09 08:14 UTC
It seems that instances of person could easily be misclassified as "hill"
![img_v3_02hd_a961476d-dac4-4b69-aa5a-c9225406586l](https://github.com/user-attachments/assets/cedbebb3-79eb-4cc2-8365-cd84716ff9f7)

**Comment by owl-10** [comment] 2024-12-09 11:31
Thank you for your attention to our work. Sorry for the error. We found that it was caused by an improper operation in prompt engineering, which was inconsistent with the method used during training. We fed 'a photo of person, child, girl, boy, woman, man, people, children, girls, boys, women, men, lady, guy, ladies, guys, clothes' into the text encoder, instead of splitting these multiple synonyms for a single class. The correct approach should have been 'a photo of person' , 'a photo of child' and so on. 

We have fixed this. You can try again now, and we hope you continue to provide us with feedback to help us improve our work.

In addition, since our mask adapter follows the standard open-vocabulary setting, training the Mask-Adapter on coco-stuff or coco-panoptic limits our mask adapter's open-vocabulary recognition ability. We will release training on additional datasets for the mask adapter in the future.

If you have any further questions, feel free to communicate with us. We hope our mask adapter work will be helpful to you.

**Comment by owl-10** [comment] 2024-12-10 06:18
After your attempt, do you still encounter the same error or any other issues? If not, we will close this issue.

**Comment by ArsenLuca** [comment] 2024-12-10 08:20
> After your attempt, do you still encounter the same error or any other issues? If not, we will close this issue.

Thanks. Things become better. U can close it. And I will open a new one if any more.

**Closed** 2024-12-10 08:22 UTC
